pos_emoticons = ['B-)', ':)', ':-)', ":')", ":'-)", ':D', ':-D', ':-)', ":')", ':o)', ':]', ':3', ':c)', ':>',
                 '=]', '8)', '=)', ':}', ':^)', '8-D', '8D', 'x-D', 'xD', 'X-D', 'XD', '=-D', '=D', '=-3', '=3',
                 'B^D', ':-))', ':*', ':^*', '( \'}{\' )', '^^', '(^_^)', '^-^', "^.^", "^3\^", "\^L\^", ':O',
                 '(:', '>:O', '>:0', ':o', 'c:', '>:o', ':d', 'd;', ': )', '^_^', '^_^*', ':0', ';o', ':x', 'd=',
                 ';)', ':-q', '<3', ':p', 'q:', ':b', ':")', ':p', ': p', ':-*', ':,)', "d':", ":-d",
                 ':^d', ':-  -d', ':-  -  -d', ':-  -  -  -d', '(x', '-)', ';-)', ':-  -  -  -  -d', "(':",
                 '(":', ':">', '(;', ': d', "(':", "(':", '*:', ';d', ':-p', '[:', ':-', ':f', ':  )))', "\(  )/", "xd",
                 '(-:', '<:', '{:', '{,:', ':-]', ';-*', "(':", 'c ,:', ':-x', '=-o', ':-0', ":'')", "(@", "dx",
                 ':---)))))', 'c":', ":'3", ":''')", '( :', ':-o', 'c  :', ':''>', ': *', ': >', ':8e', ':’)', "c':",
                 "^▁^*", "（；゜", "゜）", '^▽^']

neg_emoticons = [':(', ":'(", ":'-(", ":,(" '>:[', ':-c', ':c', ':-<', ':<', ':-[', ':[', ':{', ':-(', ':(',
                 ' _( ', ':[', "='(", "' [", "='[", ":'-<", ":' <", ":'<", "=' <", "='<", "T_T", "T.T", "(T_T)",
                 "y_y", "y.y", "(Y_Y)", ";-;", ";_;", ";.;", ":_:", "o .__. o", ".-.", ')x', '>_<', '):', ':(',
                 'd:', 'o:', '0:', '<\\3', '>.<', ']:', "]':", '/:', ": '(", ':@', '\:', ':s', '-_-', '-_-#', ":'d",
                 ':-@', '><', '>_<', '>.>', '<.<', '-.-', 't.t', ':/', ':-/', '>:/', ':\\', "<'/3", '=/',
                 ':-\\', ':|', ':-\\', ':l', '=\\', ': (', '=\\', ":'c", ":'/", ': o', ":-  /////", ':$', ':"(',
                 '-__-', '—___— ', '>  <', ")':", ':”(', ': @', ':  //', ':______x', '0.o', 'o.o', 'o_o', ' oo ',
                 '|:', ';-(', '> :', 'v:', ':, c', '#:', ':  (((((', ": ' ,(", "/':", ":'oo", '</3', '/.\\']

stopwords = ['other', 'where', 'our', 'on', 'their', 'that', 'when', 'them', 'too', 'd', 'for', 'shan', 've', 'down',
             "\'s", "'t",
             'from', 'had', 'you', 'needn', "hadn't", 'isn', 'shouldn', 'than', 'and', 'after', 'i', "that'll", 'has',
             'in', "'re", "n't",
             'here', 'do', 'ma', "weren't", 'aren', 'yourself', 'am', 'out', 'more', "aren't", 'myself', 'which',
             'mustn', 'just', "'ll",
             'll', 'y', 'are', 'while', 'how', 'won', 'herself', 'is', 'until', 'against', 'ours', 'her', 'doesn',
             "shan't", 'both', "'ve",
             'now', 'wouldn', 'your', 'his', 'itself', 'by', 'between', 'being', 'themselves', 'be', 'but', 'before',
             'again', 'haven',
             're', 'with', 'each', 'hers', 'me', 'should', 'couldn', "didn't", 'some', 'will', 't', 'if', 'once',
             "you'd", "mustn't", 'few',
             'such', 'wasn', 'during', 'been', 'hasn', 'as', 'hadn', 'over', 'under', 'we', 'yourselves', 'through',
             'all', 'who', 'further',
             "doesn't", "shouldn't", 'above', 'it', 'whom', 'the', 'didn', "it's", 'so', "'", 'these', 'those', 'off',
             'not', 'doing', 'most', 'own',
             'there', 'same', 'its', 'did', 'because', 'himself', "needn't", 'have', 'don', 'of', "she's", 'does',
             'weren', 'ain', 'then', 'very',
             'yours', 'only', 'my', "you'll", "wasn't", 'into', 'was', "couldn't", 'this', 'mightn', 'she', 'having',
             'or', 'm', 'were', 'why', 'nor',
             "hasn't", 'what', 'can', "wouldn't", 'at', "don't", 'an', 'to', 'ourselves', 'theirs', "you're", 'they',
             "you've", 'about', 'below', 'he',
             'o', "haven't", 'any', "isn't", 'up', "won't", "mightn't", "should've", 'him', 'no', 'a', 's', "would",
             "could", "go", "get", "like", "dont", "cant"]

others = ["-~*~√~*~-", '☞', '☜', '♫', '🇪🇸', '', '🇺🇸', '→', '←', '↑', '↓', '✘', '┌п┐', '★', '≫', 'ㅠ', 'ㅡ', 'ㅁ', '➜']

punctuations = ["[", ",", "?", "!", ".", ";", ":", "\\", "/", "(", ")", "&", "-", "_", "+", "=", "<", ">", "]", "{",
                "}",
                "@", "..", "...", "....", "<<", ">>", "'", '"', '﻿']

slang_words = {'afaik': 'as far as i know', 'afk': 'away from keyboard', 'asap': 'as soon as possible',
               "pic": "picture", "q": "cute",
               'atk': 'at the keyboard', 'atm': 'at the moment', 'a3': 'anytime, anywhere, anyplace', "nun": "nothing",
               "nd": "and",
               'bak': 'back at keyboard', 'bbl': 'be back later', 'bbs': 'be back soon', 'bfn': 'bye for now',
               "ima": "i am a", "im": "i am",
               'brb': 'be right back', 'brt': 'be right there', 'btw': 'by the way', 'b4n': 'bye for now',
               "idk": "i don't know",
               'cu': 'see you', 'cul8r': 'see you later', 'cya': 'see you', 'faq': 'frequently asked questions',
               "lik": "like i know",
               'fc': 'fingers crossed', 'fwiw': 'for what it\'s worth', 'fyi': 'for your information', "doe": "though",
               "ve": "have", "ya": "you all",
               'gal': 'get a life', 'gg': 'good game', 'gmta': 'great minds think alike', 'gr8': 'great',
               "welp": "well",
               'svu': "special victim's unit", "tj": "bad ass", "dd": "big breast", "thi": "this", "w|": "with",
               "wen": "when",
               'g9': 'genius', 'ic': 'i see', 'icq': 'i seek you', 'ilu': 'ilu: i love you', 'flm': "Fight like Matt",
               'imho': 'in my honest opinion', 'imo': 'in my opinion', 'iow': 'in other words', 'irl': 'in real life',
               "liq": "laugh inside quietly",
               'kiss': 'keep it simple, stupid', 'ldr': 'long distance relationship', 'lmao': 'laugh my a.. off',
               "bc": "because",
               'lol': 'laughing out loud', 'ltns': 'long time no see', 'l8r': 'later', 'mte': 'my thoughts exactly',
               "tlk": "talk",
               'm8': 'mate', 'nrn': 'no reply necessary', 'oic': 'oh i see', 'pita': 'pain in the a..', 'prt': 'party',
               "n't": "ain't",
               'prw': 'parents are watching', 'qpsa?': 'que pasa', 'rofl': 'rolling on the floor laughing', "r": "are",
               "tl": "timeline",
               'roflol': 'rolling on the floor laughing out loud',
               'rotflmao': 'rolling on the floor laughing my ass off', "sf": "stop flirting",
               'sk8': 'skate', 'stats': 'your sex and age', 'asl': 'age, sex, location', 'thx': 'thank you',
               "wk": "weekend",
               'ttfn': 'ta-ta for now!', 'ttyl': 'talk to you later', 'u': 'you', 'u2': 'you too',
               "a$ap": "as soon as possible",
               'u4e': 'yours for ever', 'wb': 'welcome back', 'wtf': 'what the f...', 'wtg': 'way to go!', "f": "fuck",
               'wuf': 'where are you from?', 'w8': 'wait...', '7k': 'sick:-d laugher', "n": "and", "ll": "will",
               "k": "ok",
               'drb': 'dumb retared bitch', "i'm": "i am", "i'd": "i would", "'m": "i am", "y": "why", "i'll": "i will",
               "'ll": "i will",
               "dis": "this", "lmfao": "laughing my fucking ass off", "kno": "know", "ikm": "i know right",
               "we've": "we have",
               "xmas": "Christmas", "couldnt": "couldn't", "ur": "your", "ctfu": "cracks the fuck up",
               "rt": "real talk", "thi": "this",
               "fwy": "fucking with you", "st": "small talk", "omg": "oh my god", "w": "with",
               "bff": "best friends forever",
               "tf": "what the fuck", "lcc": "the chubby chaser", "lb": "like back", "aer": "annual equivalent rating",
               "lil": "little",
               "y'all": "you all", "c": "see", "dunno": "don't know", "em": "them", "dmed": "damned", "gee": "pussy",
               "tryna": "trying to",
               "wazzup": "whats up", "imma": "i am going to", "bout": "about", "tx": "thanks", "th": "thanks",
               "fu": "fuck you", "wa": "whats up",
               "gtfo": "get the fuck off", "thanksgiv": "thanksgiving day", "tonit": "tonight", "bday": "birthday",
               "b-day": "birthday"}
